/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */

export type AuthByEmailFailedResponseAllOfCode =
  (typeof AuthByEmailFailedResponseAllOfCode)[keyof typeof AuthByEmailFailedResponseAllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthByEmailFailedResponseAllOfCode = {
  code_invalid_or_expired: "code_invalid_or_expired",
  null: "null",
  "[object_Object]": "[object Object]",
} as const;
