/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */

export type AuthByPasswordFailedResponseAllOfCode =
  (typeof AuthByPasswordFailedResponseAllOfCode)[keyof typeof AuthByPasswordFailedResponseAllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthByPasswordFailedResponseAllOfCode = {
  invalid_password: "invalid_password",
  password_not_set: "password_not_set",
  not_found: "not_found",
} as const;
