/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */
import type { Email } from "./email";
import type { FirstName } from "./firstName";
import type { Language } from "./language";
import type { LastName } from "./lastName";
import type { Name } from "./name";
import type { Role } from "./role";
import type { Theme } from "./theme";

export interface Me {
  readonly name: Name;
  readonly firstName?: FirstName;
  readonly lastName?: LastName;
  readonly role: Role;
  readonly email?: Email;
  readonly language: Language;
  readonly theme: Theme;
  readonly isEmailVerified: boolean;
}
