/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */

export type SendCodeErrorResponseAllOfCode =
  (typeof SendCodeErrorResponseAllOfCode)[keyof typeof SendCodeErrorResponseAllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendCodeErrorResponseAllOfCode = {
  cant_send_mail: "cant_send_mail",
  transaction_failed: "transaction_failed",
  server_error: "server_error",
} as const;
