/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */
import type { Avatar } from "./avatar";
import type { Biography } from "./biography";
import type { CreateTime } from "./createTime";
import type { Email } from "./email";
import type { FirstName } from "./firstName";
import type { FriendsIds } from "./friendsIds";
import type { IsEmailVerified } from "./isEmailVerified";
import type { Language } from "./language";
import type { LastName } from "./lastName";
import type { Name } from "./name";
import type { Role } from "./role";
import type { Theme } from "./theme";

export interface Session {
  readonly name: Name;
  readonly email: Email;
  readonly role: Role;
  readonly friendsIds?: FriendsIds;
  readonly language: Language;
  readonly theme: Theme;
  readonly firstName?: FirstName;
  readonly lastName?: LastName;
  readonly biography?: Biography;
  readonly createTime: CreateTime;
  readonly isEmailVerified: IsEmailVerified;
  readonly avatar: Avatar;
}
