/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */
import type { Biography } from "./biography";
import type { FirstName } from "./firstName";
import type { Language } from "./language";
import type { LastName } from "./lastName";
import type { Theme } from "./theme";

export type UserPatchBody = {
  firstName?: FirstName;
  lastName?: LastName;
  biography?: Biography;
  theme?: Theme;
  language?: Language;
};
