/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */

export type UserNamePatchFailedResponseAllOfCode =
  (typeof UserNamePatchFailedResponseAllOfCode)[keyof typeof UserNamePatchFailedResponseAllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserNamePatchFailedResponseAllOfCode = {
  invalid_validation: "invalid_validation",
  already_exist: "already_exist",
} as const;
