/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */

export type UserPatchFailedResponseAllOfCode =
  (typeof UserPatchFailedResponseAllOfCode)[keyof typeof UserPatchFailedResponseAllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserPatchFailedResponseAllOfCode = {
  invalid_validation: "invalid_validation",
} as const;
