/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * YouTogether API
 * This is CRUD API documentation for you-together-online project.
You can get more info about that project [here](https://github.com/youtogether-online)
 * OpenAPI spec version: 1.0.0
 */

export type WebsocketConnectionFailedResponseAllOfCode =
  (typeof WebsocketConnectionFailedResponseAllOfCode)[keyof typeof WebsocketConnectionFailedResponseAllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WebsocketConnectionFailedResponseAllOfCode = {
  websocket_excepted: "websocket_excepted",
} as const;
